#!/usr/bin/env python3


import random

def main():

    wordbank= ["indentation", "spaces"] 

    tlgstudents= ["Aaron", "Andy", "Asif", "Brent", "Cedric", "Chris", "Cory", "Ebrima", "Franco", "Greg", "Hoon", "Joey", "Jordan", "JC", "LB", "Mabel", "Shon", "Pat", "Zach"]

    print(tlgstudents)

    wordbank.append(4)
    print(wordbank)


    num= int(input(f"Pick a student number between 1 and {len(tlgstudents)} --> !"))-1
    name = tlgstudents[num]
    print(f"Your unfortante victim is {name}!")
    print(f"{name} always uses {wordbank[2]} to indent.")

    name = random.choice(tlgstudents)
    print(f"{name}")

if __name__ == "__main__":
    main()


